services:
    postgres:
        image: postgres:15
        container_name: postgres_15
        environment:
            POSTGRES_USER: postgres_user
            POSTGRES_PASSWORD: postgres_password
            POSTGRES_DB: postgres_db
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    mysql:
        image: mysql:8
        container_name: mysql_8
        environment:
            MYSQL_ROOT_PASSWORD: mysql_root_password
            MYSQL_DATABASE: mysql_db
            MYSQL_USER: mysql_user
            MYSQL_PASSWORD: mysql_password
        ports:
            - "3308:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    mariadb:
        image: mariadb:11
        container_name: mariadb_11
        environment:
            MARIADB_ROOT_PASSWORD: mariadb_root_password
            MARIADB_DATABASE: mariadb_db
            MARIADB_USER: mariadb_user
            MARIADB_PASSWORD: mariadb_password
        ports:
            - "3309:3306"
        volumes:
            - mariadb_data:/var/lib/mysql

    mongodb:
      image: mongodb/mongodb-community-server:6.0-ubi8
      environment:
        - MONGODB_INITDB_ROOT_USERNAME=eavlongs
        - MONGODB_INITDB_ROOT_PASSWORD=ErtrwdxAnfU3KHLQ
      ports:
        - "27017:27017"
      volumes:
        - mongodb_data:/var/lib/mongodb/data

volumes:
    postgres_data:
    mysql_data:
    mariadb_data:
    mongodb_data:
